### ISSUE TITLE
@vueuse/nuxt + @vueuse/integrations [autoImport]

### ISSUE THREAD

**Issue by emilsgulbis** [vueuse/vueuse#1306]
### Describe the bug

<img width="1004" alt="Screenshot 2022-02-22 at 09 57 47" src="https://user-images.githubusercontent.com/3534160/155087753-67affab8-79a7-452c-8002-8991a9f11bb1.png">

To enable `autoImport` it's required to manually install every relational dependency?

### Reproduction

https://stackblitz.com/edit/nuxt-starter-pazvmc?

### System Info

```Shell
System:
    OS: macOS 12.1
    CPU: (8) arm64 Apple M1
    Memory: 120.95 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.0.1 - /opt/homebrew/bin/node
    Yarn: 1.22.15 - /opt/homebrew/bin/yarn
    npm: 8.1.0 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 98.0.4758.102
    Firefox: 96.0.3
    Safari: 15.2
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by MasterEros** [comment]
yarn add universal-cookie

**Comment by antfu** [comment]
Fixed in 18ba05ea4e963bc0474d89de9f802df798ad52bd

**Comment by antfu** [comment]
Fixed in 18ba05ea4e963bc0474d89de9f802df798ad52bd

**Comment by MCYouks** [comment]
I am encountering the same issue using the latest version of Nuxt 3. Did I miss something?

**Comment by projct1** [comment]
Autoimports still not working :"(
Without `import { useDebounceFn } from '@vueuse/core'` got error: `500 useDebounceFn is not defined` =\
```vue
<script setup lang="ts">
const search = useDebounceFn(async q => {
    //some code
}, 500)
</script>
```

**Comment by m-shum** [comment]
Getting undefined errors with:
```
"@vueuse/core": "^12.5.0",
"@vueuse/nuxt": "^12.5.0",
```
But not with:
```
"@vueuse/core": "^12.4.0",
"@vueuse/nuxt": "^12.4.0",
```

**Comment by ilyaliao** [comment]
> 自動匯入不適用於：
> 
> ```
> "@vueuse/core": "^12.5.0",
> "@vueuse/nuxt": "^12.5.0",
> ```
> 
> 但與以下人員合作：
> 
> ```
> "@vueuse/core": "^12.4.0",
> "@vueuse/nuxt": "^12.4.0",
> ```
> 
> 確實注意到當我運行時錯誤消失了`npx nuxi@latest module add vueuse`。然後，我清除了節點模組和包鎖，並按照文件重新執行常規 npm 命令`npm i @vueuse/nuxt @vueuse/core`，自動導入再次中斷。

can you open a new issue and provide minimal reproduction, please?

**Comment by ilyaliao** [comment]
> Autoimports not working with:
> 
> ```
> "@vueuse/core": "^12.5.0",
> "@vueuse/nuxt": "^12.5.0",
> ```
> 
> But working with:
> 
> ```
> "@vueuse/core": "^12.4.0",
> "@vueuse/nuxt": "^12.4.0",
> ```
> 
> Did notice that the error went away when I ran `npx nuxi@latest module add vueuse`. I then cleared node-modules and package-lock and re-ran the regular npm command as per the docs `npm i @vueuse/nuxt @vueuse/core` and autoimports broke again.

can you open a new issue and provide minimal reproduction, please?
