### ISSUE TITLE
Cannot run dev on windows: yarn dev

### ISSUE THREAD

**Issue by userquin** [vueuse/vueuse#337]
I have clone this repo and `yarn dev` just not working:
```shell
F:\work\projects\quini\vite-vitesse-2\vueuse>node --version
v15.5.1

F:\work\projects\quini\vite-vitesse-2\vueuse>yarn --version
1.22.10

F:\work\projects\quini\vite-vitesse-2\vueuse>yarn list vite
yarn list v1.22.10
warning Filtering by arguments is deprecated. Please use the pattern option instead.
└─ vite@2.0.1
Done in 0.68s.

F:\work\projects\quini\vite-vitesse-2\vueuse>yarn list vue
yarn list v1.22.10
warning Filtering by arguments is deprecated. Please use the pattern option instead.
└─ vue@3.0.5
Done in 0.68s.

```

Install dependencies:

```shell
F:\work\projects\quini\vite-vitesse-2\vueuse>yarn install
yarn install v1.22.10
[1/4] Resolving packages...
[2/4] Fetching packages...
warning Pattern ["vue-demi@latest"] is trying to unpack in the same destination "C:\\Users\\userquin\\AppData\\Local\\Yarn\\Cache\\v6\\npm-vue-demi-0.6.0-e314282f704cb449119b9fd002cbbc0e39f591fe-integrity\\node
_modules\\vue-demi" as pattern ["vue-demi@^0.6.0","vue-demi@^0.6.0"]. This could result in non-deterministic behavior, skipping.
info fsevents@2.1.3: The platform "win32" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.3.1: The platform "win32" is incompatible with this module.
info "fsevents@2.3.1" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.3.2: The platform "win32" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > @rollup/plugin-typescript@8.2.0" has unmet peer dependency "tslib@*".
warning " > @vue/test-utils@1.1.3" has incorrect peer dependency "vue@2.x".
warning " > @vue/test-utils@1.1.3" has unmet peer dependency "vue-template-compiler@^2.x".
warning " > babel-loader@8.2.2" has unmet peer dependency "webpack@>=2".
warning " > esbuild-register@2.0.0" has unmet peer dependency "esbuild@>=0.8.31".
warning " > rollup-plugin-uglify@6.0.4" has incorrect peer dependency "rollup@>=0.66.0 <2".
warning " > vite-plugin-components@0.6.12" has unmet peer dependency "vite@^2.0.0-beta.69".
warning " > vite-plugin-icons@0.2.2" has unmet peer dependency "@vue/compiler-sfc@^3.0.2".
warning "vitepress > @docsearch/js > @docsearch/react@1.0.0-alpha.28" has unmet peer dependency "react@^16.8.0".
warning "vitepress > @docsearch/js > @docsearch/react@1.0.0-alpha.28" has unmet peer dependency "react-dom@^16.8.0".
warning " > @vue/composition-api@1.0.0-rc.2" has incorrect peer dependency "vue@>= 2.5 < 3".
warning " > @vueuse/router@4.2.0-beta.2" has unmet peer dependency "vue-router@>=4.0.0-rc.1".
warning " > @vueuse/rxjs@4.2.0-beta.2" has unmet peer dependency "rxjs@>=6.0.0".
[4/4] Building fresh packages...
success Saved lockfile.
$ patch-package
patch-package 6.2.2
Applying patches...
No patch files found
Done in 107.79s.
```

and starting vitepress:

```shell
F:\work\projects\quini\vite-vitesse-2\vueuse>yarn dev
yarn run v1.22.10
$ nr docs
$ vitepress dev packages
vitepress v0.12.2
vite v2.0.1
(!) "alias" option is deprecated. Use "resolve.alias" instead.
Pre-bundling dependencies:
  qrcode
  nprogress
  tslib
  js-yaml
  dayjs
  (...and 3 more)
(this will be run only when your dependencies or config have changed)

 ⚡ Vite dev server running at:

  > Network:  http://192.168.1.37:3000/
  > Local:    http://localhost:3000/
  > Network:  http://172.17.94.17:3000/
[@vue/compiler-sfc] <script setup> is still an experimental proposal.
Follow its status at https://github.com/vuejs/rfcs/pull/227.

[@vue/compiler-sfc] When using experimental features,
it is recommended to pin your vue dependencies to exact versions to avoid breakage.

11:28:02 [vite] new dependencies found: vue-chemistry/boolean, updating...
11:28:02 [vite] ✨ dependencies updated, reloading page...
11:28:02 [vite] Internal server error: Failed to resolve entry for package "@vueuse/core". The package may have incorrect main/module/exports specified in its package.json.
  Plugin: vite:import-analysis
  File: F:/work/projects/quini/vite-vitesse-2/vueuse/packages/.vitepress/theme/components/DarkModeSwitch.vue
      at resolvePackageEntry (F:\work\projects\quini\vite-vitesse-2\vueuse\node_modules\vite\dist\node\chunks\dep-d13406fa.js:34262:15)
      at tryNodeResolve (F:\work\projects\quini\vite-vitesse-2\vueuse\node_modules\vite\dist\node\chunks\dep-d13406fa.js:34102:11)
      at Context.resolveId (F:\work\projects\quini\vite-vitesse-2\vueuse\node_modules\vite\dist\node\chunks\dep-d13406fa.js:33985:28)
      at Object.resolveId (F:\work\projects\quini\vite-vitesse-2\vueuse\node_modules\vite\dist\node\chunks\dep-d13406fa.js:45841:55)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:93:5)
      at async TransformContext.resolve (F:\work\projects\quini\vite-vitesse-2\vueuse\node_modules\vite\dist\node\chunks\dep-d13406fa.js:45646:23)
      at async normalizeUrl (F:\work\projects\quini\vite-vitesse-2\vueuse\node_modules\vite\dist\node\chunks\dep-d13406fa.js:47179:34)
      at async TransformContext.transform (F:\work\projects\quini\vite-vitesse-2\vueuse\node_modules\vite\dist\node\chunks\dep-d13406fa.js:47318:57)
      at async Object.transform (F:\work\projects\quini\vite-vitesse-2\vueuse\node_modules\vite\dist\node\chunks\dep-d13406fa.js:45898:30)
11:28:21 [vite] Internal server error: Failed to resolve entry for package "@vueuse/core". The package may have incorrect main/module/exports specified in its package.json.
  Plugin: vite:import-analysis
  File: F:/work/projects/quini/vite-vitesse-2/vueuse/packages/.vitepress/theme/components/DarkModeSwitch.vue
      at resolvePackageEntry (F:\work\projects\quini\vite-vitesse-2\vueuse\node_modules\vite\dist\node\chunks\dep-d13406fa.js:34262:15)
      at tryNodeResolve (F:\work\projects\quini\vite-vitesse-2\vueuse\node_modules\vite\dist\node\chunks\dep-d13406fa.js:34102:11)
      at Context.resolveId (F:\work\projects\quini\vite-vitesse-2\vueuse\node_modules\vite\dist\node\chunks\dep-d13406fa.js:33985:28)
      at Object.resolveId (F:\work\projects\quini\vite-vitesse-2\vueuse\node_modules\vite\dist\node\chunks\dep-d13406fa.js:45841:55)
      at processTicksAndRejections (node:internal/process/task_queues:93:5)
      at async TransformContext.resolve (F:\work\projects\quini\vite-vitesse-2\vueuse\node_modules\vite\dist\node\chunks\dep-d13406fa.js:45646:23)
      at async normalizeUrl (F:\work\projects\quini\vite-vitesse-2\vueuse\node_modules\vite\dist\node\chunks\dep-d13406fa.js:47179:34)
      at async TransformContext.transform (F:\work\projects\quini\vite-vitesse-2\vueuse\node_modules\vite\dist\node\chunks\dep-d13406fa.js:47318:57)
      at async Object.transform (F:\work\projects\quini\vite-vitesse-2\vueuse\node_modules\vite\dist\node\chunks\dep-d13406fa.js:45898:30)
      at async transformRequest (F:\work\projects\quini\vite-vitesse-2\vueuse\node_modules\vite\dist\node\chunks\dep-d13406fa.js:61468:29)
¿Desea terminar el trabajo por lotes (S/N)? s
```

**Comment by userquin** [comment]
`yarn.lock` is modified adding this entry when running `yarn install`, shouldn't be modified:

![imagen](https://user-images.githubusercontent.com/6311119/108622846-cc098300-743b-11eb-9dd6-fd7f0d894db2.png)

**Comment by YunYouJun** [comment]
After `yarn install` & `yarn dev`.
I can open homepage. But i get this when i click `useXXX` to see demo.

`[vite] Internal server error: Cannot import non-asset file /../.vitepress/theme/components/DemoContainer.vue which is inside /public.JS/CSS files inside /public are copied as-is on build and can only be referenced via <script src> or <link href> in html.`

```sh
2:52:24 AM [vite] Internal server error: Cannot import non-asset file /../.vitepress/theme/components/DemoContainer.vue which is inside /public.JS/CSS files inside /public are copied as-is on build and can only be referenced via <script src> or <link href> in html.
  Plugin: vite:import-analysis
  File: /Users/yunyou/github/rf/vueuse/packages/core/useBrowserLocation/index.md
      at TransformContext.transform (/Users/yunyou/github/rf/vueuse/node_modules/vite/dist/node/chunks/dep-d13406fa.js:47313:31)
      at async Object.transform (/Users/yunyou/github/rf/vueuse/node_modules/vite/dist/node/chunks/dep-d13406fa.js:45898:30)
      at async transformRequest (/Users/yunyou/github/rf/vueuse/node_modules/vite/dist/node/chunks/dep-d13406fa.js:61468:29)
      at async /Users/yunyou/github/rf/vueuse/node_modules/vite/dist/node/chunks/dep-d13406fa.js:61570:32
```

Is there any solution to it?

**Comment by antfu** [comment]
I think there is some edge case of Vite not awaring of linked packages in monorepo, you can try to `yarn build` and then try `yarn dev`?

**Comment by YunYouJun** [comment]
> I think there is some edge case of Vite not awaring of linked packages in monorepo, you can try to `yarn build` and then try `yarn dev`?

I have tried this, but no work.

It seems that only `DemoContainer` is not loaded properly. Other content works well.

`DemoContainer` is imported and autoloaded by `vite-plugin-components`. Is it related to this?

https://github.com/vueuse/vueuse/blob/5941b6a64e556846d4f8492d4215c460febc4881/packages/.vitepress/theme/index.ts#L3

https://github.com/vueuse/vueuse/blob/5941b6a64e556846d4f8492d4215c460febc4881/packages/vite.config.ts#L42

**Comment by userquin** [comment]
@antfu sorry for the delay, it works with `yarn build` previous to `yarn dev`

**Comment by userquin** [comment]
but all sensor entries 404

**Comment by userquin** [comment]
all entries with 404

**Comment by userquin** [comment]
maybe `yarn link` + `yarn link @vueuse/core` + `yarn link @vueuse/shared` after build:

```shell
yarn
yarn build
yarn link
yarn link @vueuse/core
yarn link @vueuse/shared
```

**Comment by antfu** [comment]
Yeah, can confirm. Might be some bug introduced in the latest deps bump, I'll look into it. Thanks.

**Comment by userquin** [comment]
iief and  umd last changes?

**Comment by antfu** [comment]
Should be fixed in the latest commits.

**Comment by userquin** [comment]
@antfu confirmed, last changes works, also `yarn.lock` not modified.

just `yarn install` + `yarn dev`, there is no need to build it.

**Comment by userquin** [comment]
but still getting some errors, I need to refresh function pages:
```shell
21:30:10 [vite] Internal server error: end of the stream or a document separator is expected at line 7, column 9:
    category: Sensors
            ^
  Plugin: vitepress
  File: F:/work/projects/quini/vite-vitesse-2/vueuse/packages/core/useSwipe/index.md
      at generateError (F:\work\projects\quini\vite-vitesse-2\vueuse\node_modules\gray-matter\node_modules\js-yaml\lib\js-yaml\loader.js:167:10)
      at throwError (F:\work\projects\quini\vite-vitesse-2\vueuse\node_modules\gray-matter\node_modules\js-yaml\lib\js-yaml\loader.js:173:9)
      at readDocument (F:\work\projects\quini\vite-vitesse-2\vueuse\node_modules\gray-matter\node_modules\js-yaml\lib\js-yaml\loader.js:1545:5)
      at loadDocuments (F:\work\projects\quini\vite-vitesse-2\vueuse\node_modules\gray-matter\node_modules\js-yaml\lib\js-yaml\loader.js:1588:5)
      at load (F:\work\projects\quini\vite-vitesse-2\vueuse\node_modules\gray-matter\node_modules\js-yaml\lib\js-yaml\loader.js:1614:19)
      at Object.safeLoad (F:\work\projects\quini\vite-vitesse-2\vueuse\node_modules\gray-matter\node_modules\js-yaml\lib\js-yaml\loader.js:1637:10)
      at module.exports (F:\work\projects\quini\vite-vitesse-2\vueuse\node_modules\gray-matter\lib\parse.js:12:17)
      at parseMatter (F:\work\projects\quini\vite-vitesse-2\vueuse\node_modules\gray-matter\index.js:109:17)
      at Object.matter [as default] (F:\work\projects\quini\vite-vitesse-2\vueuse\node_modules\gray-matter\index.js:50:10)
      at F:\work\projects\quini\vite-vitesse-2\vueuse\node_modules\vitepress\dist\node\markdownToVue.js:26:69
21:30:31 [vite] Internal server error: end of the stream or a document separator is expected at line 7, column 9:
    category: Browser
            ^
  Plugin: vitepress
  File: F:/work/projects/quini/vite-vitesse-2/vueuse/packages/core/useBrowserLocation/index.md
      at generateError (F:\work\projects\quini\vite-vitesse-2\vueuse\node_modules\gray-matter\node_modules\js-yaml\lib\js-yaml\loader.js:167:10)
      at throwError (F:\work\projects\quini\vite-vitesse-2\vueuse\node_modules\gray-matter\node_modules\js-yaml\lib\js-yaml\loader.js:173:9)
      at readDocument (F:\work\projects\quini\vite-vitesse-2\vueuse\node_modules\gray-matter\node_modules\js-yaml\lib\js-yaml\loader.js:1545:5)
      at loadDocuments (F:\work\projects\quini\vite-vitesse-2\vueuse\node_modules\gray-matter\node_modules\js-yaml\lib\js-yaml\loader.js:1588:5)
      at load (F:\work\projects\quini\vite-vitesse-2\vueuse\node_modules\gray-matter\node_modules\js-yaml\lib\js-yaml\loader.js:1614:19)
      at Object.safeLoad (F:\work\projects\quini\vite-vitesse-2\vueuse\node_modules\gray-matter\node_modules\js-yaml\lib\js-yaml\loader.js:1637:10)
      at module.exports (F:\work\projects\quini\vite-vitesse-2\vueuse\node_modules\gray-matter\lib\parse.js:12:17)
      at parseMatter (F:\work\projects\quini\vite-vitesse-2\vueuse\node_modules\gray-matter\index.js:109:17)
      at Object.matter [as default] (F:\work\projects\quini\vite-vitesse-2\vueuse\node_modules\gray-matter\index.js:50:10)
      at F:\work\projects\quini\vite-vitesse-2\vueuse\node_modules\vitepress\dist\node\markdownToVue.js:26:69
```

**Comment by userquin** [comment]
I have deleted repo, cloned it again, removed from local filesystem and checkout from my fork...

**Comment by userquin** [comment]
also failing building it...

Why `yarn build` touches some index.ts files?

**Comment by userquin** [comment]
![imagen](https://user-images.githubusercontent.com/6311119/108638427-7f4f9780-748f-11eb-919d-6b1166920c0a.png)

**Comment by antfu** [comment]
Can you provide more context? And yeah, `index.ts` is generated, it should not be changed unless you touched something related.

**Comment by YunYouJun** [comment]
I pull the latest code. And it works.

**Comment by antfu** [comment]
Alright, I am closing this now. Thank you guys for the reporting.
