### ISSUE TITLE
BUG | `useMediaQuery` |  v14 breaks nuxt build

### ISSUE THREAD

**Issue by LidoToursDev** [vueuse/vueuse#5114]
### Describe the bug

Hi,

After upgrading to vueuse v14, nuxt production builds break with:

```js
(...)
Generated public .output/public                                              nitro 16:04:37
[nitro 16:04:37] ℹ Building Nuxt Nitro server (preset: node-server, compatibility date: 2025-07-08)

[nitro 16:04:38]  ERROR  RollupError: Expected ',', got '$1' in /home/projects/github-gzbuzr-dza8cnjg/node_modules/.cache/nuxt/.nuxt/dist/server/_nuxt/index-BHAFmpKj.js


 99: function useMediaQuery(query, options = {}) {
100:   const { window: window$1 = defaultWindow, ssrWidth = /* @__PURE__ */ useSSRWidth() } = options;
101:   const isSupported = /* @__PURE__ */ useSupported(() => window$1 && "matchMedia" in window$1 && "undefined"$1.matchMe...
                                                                                                                 ^
102:   const ssrSupport = shallowRef(typeof ssrWidth === "number");
103:   const mediaQuery = shallowRef();


[16:04:38]  ERROR  Expected ',', got '$1' in /home/projects/github-gzbuzr-dza8cnjg/node_modules/.cache/nuxt/.nuxt/dist/server/_nuxt/index-BHAFmpKj.js

    at getRollupError (node_modules/.pnpm/rollup@4.46.1/node_modules/rollup/dist/es/shared/parseAst.js:568:41)
    at convertProgram (node_modules/.pnpm/rollup@4.46.1/node_modules/rollup/dist/es/shared/parseAst.js:1265:26)
    at parseAst (node_modules/.pnpm/rollup@4.46.1/node_modules/rollup/dist/es/shared/parseAst.js:2250:87)
    at tryParse (node_modules/.pnpm/@rollup+plugin-commonjs@28.0.6_rollup@4.46.1/node_modules/@rollup/plugin-commonjs/dist/es/index.js:32:12)
    at analyzeTopLevelStatements (node_modules/.pnpm/@rollup+plugin-commonjs@28.0.6_rollup@4.46.1/node_modules/@rollup/plugin-commonjs/dist/es/index.js:52:15)
    at Object.transformAndCheckExports (node_modules/.pnpm/@rollup+plugin-commonjs@28.0.6_rollup@4.46.1/node_modules/@rollup/plugin-commonjs/dist/es/index.js:2132:68)
    at Object.transform (node_modules/.pnpm/@rollup+plugin-commonjs@28.0.6_rollup@4.46.1/node_modules/@rollup/plugin-commonjs/dist/es/index.js:2336:41)
    at eval (node_modules/.pnpm/rollup@4.46.1/node_modules/rollup/dist/es/shared/node-entry.js:22370:40)
    at <anonymous> (https://githubgzbuzrdza8cnjg-a2r0.w-credentialless-staticblitz.com/blitz.96435430.js:31:29397) 



[16:04:38]  ERROR  Expected ',', got '$1' in /home/projects/github-gzbuzr-dza8cnjg/node_modules/.cache/nuxt/.nuxt/dist/server/_nuxt/index-BHAFmpKj.js

 ELIFECYCLE  Command failed with exit code 1.

~/projects/github-gzbuzr-dza8cnjg
```

Running locally in development mode appears to be ok and shows no errors. 

Downgrading back to v13.9 appears to solve the production build error.

Cheers!

### Reproduction

https://stackblitz.com/edit/github-gzbuzr-dza8cnjg?file=app%2Fpages%2Findex.vue

### System Info

```Shell
System:
    OS: macOS 15.6.1
    CPU: (8) arm64 Apple M1
    Memory: 246.64 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 24.4.1 - /usr/local/bin/node
    Yarn: 4.10.3 - /usr/local/bin/yarn
    npm: 11.4.2 - /usr/local/bin/npm
    bun: 1.1.33 - /Users/user/.bun/bin/bun
  Browsers:
    Chrome: 141.0.7390.122
    Firefox: 144.0
    Safari: 18.6
  npmPackages:
    @vueuse/components: ^14.0.0 => 14.0.0 
    @vueuse/core: ^14.0.0 => 14.0.0 
    @vueuse/nuxt: ^14.0.0 => 14.0.0
```

### Used Package Manager

pnpm

### Validations

- [x] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [x] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [x] Read the [docs](https://vueuse.org/guide).
- [x] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [x] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ggAbove** [comment]
same

**Comment by rylanharper** [comment]
This is not isolated to `useMediaQuery`. Its v14 in general.

**Comment by 9romise** [comment]
Hi! Thanks for the report.

1. Initial check shows this is related to how `rolldown` renames local `window` variables to `window$1` during bundling.
2. `nitro` will replace `typeof window` with hardcode `"undefined"` by using `@rollup/plugin-replace` - https://github.com/nitrojs/nitro/blob/main/src/build/config.ts#L52, so that there will be an invalid code: `"undefined"$1`
3. The `@rollup/plugin-inject` used in `nitro` appears unable to correctly parse the AST in this case and throws the error.

~~This likely affects all methods implementing the `ConfigurableWindow` interface.~~
This affects all methods that implement the `ConfigurableWindow` interface and use `typeof window` in their logic and methods on top of them.

I'll keep this thread updated with any progress.

**Comment by 9romise** [comment]
#5116 should resolve this issue. If anyone would like to try it before the official release, you can test it via `pkg.pr.new`: https://github.com/vueuse/vueuse/pull/5116#issuecomment-3435168688

**Comment by pi0** [comment]
Backporting for Nitro v2 (used by current Nuxt): https://github.com/nitrojs/nitro/pull/3672

**Comment by pi0** [comment]
Should be fixed in [nitropack@2.12.8](https://github.com/nitrojs/nitro/releases/tag/v2.12.8)

**Comment by sewalsh** [comment]
I've updated to 2.12.8 but still getting the same build breaking error.

``` zsh
pnpm why nitropack
Legend: production dependency, optional only, dev only

devDependencies:
@vueuse/nuxt 14.0.0
└─┬ nuxt 4.2.0 peer
  └─┬ @nuxt/nitro-server 4.2.0
    └── nitropack 2.12.8
nuxt 4.2.0
└─┬ @nuxt/nitro-server 4.2.0
  └── nitropack 2.12.8
```

**Comment by erwanjugand** [comment]
@sewalsh nitropack 2.12.9 fixes it :)
